package(default_visibility = ["//visibility:private"])

cc_test(
    name = "phtree_test",
    timeout = "long",
    srcs = [
        "phtree_test.cc",
    ],
    linkstatic = True,
    deps = [
        "@phtree//phtree",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "phtree_multimap_box_d_test",
    timeout = "long",
    srcs = [
        "phtree_multimap_box_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "@phtree//phtree",
        "@gtest//:gtest_main",
    ],
)
